spring:
  profiles:
    active: @env@
#mybatis
mybatis:
  type-aliases-package: com.mipo.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
server:
  connection-timeout: 20000
  port: 8888

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    #开启模板缓存（默认值：true）
    cache: true
    #Check that the template exists before rendering it.
    check-template: true
    #检查模板位置是否正确（默认值:true）
    check-template-location: true
    #开启MVC Thymeleaf视图解析（默认值：true）
    #enabled: true
    #模板编码
    encoding: UTF-8
    #要被排除在解析之外的视图名称列表，用逗号分隔
    spring.thymeleaf.excluded-view-names:
    #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML5
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，
    #只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    #template-resolver-order:
    #可解析的视图名称列表，用逗号分隔
    #spring.thymeleaf.view-names:
