spring:
  profiles:
    active: @env@
  resources:
    static-locations: classpath:/static/, classpath:/templates/
#mybatis
mybatis:
  type-aliases-package: com.mipo.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
server:
  connection-timeout: 20000
  port: 8888

#  # THYMELEAF (ThymeleafAutoConfiguration)
#  thymeleaf:
#    cache: true
#    #Check that the template exists before rendering it.
#    check-template: true
#    #检查模板位置是否正确（默认值:true）
#    check-template-location: true
#    #开启MVC Thymeleaf视图解析（默认值：true）
#    #enabled: true
#    encoding: UTF-8
#    #要被排除在解析之外的视图名称列表，用逗号分隔
#    spring.thymeleaf.excluded-view-names:
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html

